import { Farm, DiseaseReport, Diagnosis, Alert } from '@/types';
import { SEED_CROPS } from './crops';
import { SEED_DISEASES } from './diseases';

// Reference Primary Demo Farm (Odisha Kharif Rice - Panicle Initiation stage)
export const DEMO_FARM_ID = 'demo-farm-odisha-01';
export const DEMO_USER_ID = 'demo-user-ramesh-patra';

export const DEMO_PRIMARY_FARM: Farm = {
  id: DEMO_FARM_ID,
  user_id: DEMO_USER_ID,
  name: 'Bidyadharpur Model Paddy Farm',
  lat: 20.4625,
  lng: 85.8828,
  area_acres: 3.5,
  crop_id: 'rice',
  crop: SEED_CROPS[0],
  variety: 'Swarna (MTU 7029)',
  sowing_date: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // 55 days ago (Panicle Initiation)
  is_demo: true,
  created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
};

// 45 Neighboring Farms distributed around Cuttack, Bhubaneswar, Puri, and Balasore
const REGION_OFFSETS = [
  // Cuttack Outbreak Hub (within 1 - 5 km)
  { name: 'Niali Rice Plot A', lat: 20.4680, lng: 85.8910, area: 2.2, crop: 'rice', var: 'Pooja', days: 54 },
  { name: 'Niali Rice Plot B', lat: 20.4570, lng: 85.8750, area: 4.0, crop: 'rice', var: 'Swarna', days: 56 },
  { name: 'Salepur Green Farm', lat: 20.4720, lng: 85.8890, area: 3.0, crop: 'rice', var: 'Lalat', days: 50 },
  { name: 'Kisan Nagar Field 1', lat: 20.4510, lng: 85.8950, area: 1.8, crop: 'rice', var: 'Swarna', days: 58 },
  { name: 'Kisan Nagar Field 2', lat: 20.4650, lng: 85.8690, area: 5.2, crop: 'rice', var: 'MTU 1010', days: 52 },
  { name: 'Choudwar Paddy Field', lat: 20.5120, lng: 85.9120, area: 2.5, crop: 'rice', var: 'Pooja', days: 48 },
  { name: 'Jagatpur Agro Farm', lat: 20.4900, lng: 85.9200, area: 3.8, crop: 'rice', var: 'Swarna Sub-1', days: 60 },
  { name: 'Mahanga Crop Field', lat: 20.5340, lng: 86.0120, area: 4.5, crop: 'rice', var: 'Sarala', days: 62 },
  { name: 'Baranga Mixed Farm', lat: 20.3950, lng: 85.8250, area: 2.0, crop: 'tomato', var: 'Utkal Kumari', days: 40 },
  { name: 'Trisulia Agro Plot', lat: 20.4210, lng: 85.8390, area: 3.2, crop: 'rice', var: 'Swarna', days: 53 },
  // Khordha / Bhubaneswar Outer
  { name: 'Balianta Valley Plot', lat: 20.3120, lng: 85.8900, area: 2.8, crop: 'rice', var: 'Lalat', days: 45 },
  { name: 'Balipatna Agri Trust', lat: 20.2540, lng: 85.9250, area: 6.0, crop: 'rice', var: 'Swarna', days: 55 },
  { name: 'Jatani Hybrid Farm', lat: 20.1650, lng: 85.7050, area: 3.5, crop: 'maize', var: 'HQPM-1', days: 38 },
  { name: 'Khurda Rural Farm 1', lat: 20.1800, lng: 85.6200, area: 4.2, crop: 'rice', var: 'Mandakini', days: 49 },
  { name: 'Begunia Agri Cluster', lat: 20.2100, lng: 85.4900, area: 5.0, crop: 'rice', var: 'Pooja', days: 52 },
  // Puri Coastal Belt
  { name: 'Pipili Farmstead', lat: 20.1150, lng: 85.8320, area: 2.4, crop: 'rice', var: 'Swarna', days: 57 },
  { name: 'Delanga Bio Field', lat: 19.9850, lng: 85.7600, area: 3.1, crop: 'rice', var: 'Pratikhya', days: 61 },
  { name: 'Nimapada Paddy Zone', lat: 20.0650, lng: 86.0150, area: 4.8, crop: 'rice', var: 'Swarna', days: 56 },
  { name: 'Gop Organic Farm', lat: 19.9950, lng: 86.0050, area: 1.9, crop: 'tomato', var: 'Pusa Ruby', days: 45 },
  { name: 'Kakatpur Delta Farm', lat: 20.0150, lng: 86.1350, area: 3.6, crop: 'rice', var: 'Moti', days: 65 },
  // Balasore & Jagatsinghpur Zone
  { name: 'Tirtol Canal Plot', lat: 20.3150, lng: 86.3200, area: 2.7, crop: 'rice', var: 'Sarala', days: 58 },
  { name: 'Raghunathpur Farm', lat: 20.3550, lng: 86.1950, area: 3.3, crop: 'rice', var: 'Swarna', days: 54 },
  { name: 'Balasore Coastal Rice 1', lat: 21.4950, lng: 86.9320, area: 4.1, crop: 'rice', var: 'Khandagiri', days: 51 },
  { name: 'Soro Agro Center', lat: 21.2850, lng: 86.6900, area: 5.5, crop: 'rice', var: 'Swarna', days: 57 },
  { name: 'Bhadrak River Basin', lat: 21.0550, lng: 86.5100, area: 3.9, crop: 'rice', var: 'Pooja', days: 53 },
  { name: 'Jajpur Paddy Hub', lat: 20.8450, lng: 86.3350, area: 4.6, crop: 'rice', var: 'Swarna', days: 55 },
  { name: 'Dhenkanal Valley', lat: 20.6650, lng: 85.6010, area: 2.9, crop: 'maize', var: 'Bio-9681', days: 42 },
  { name: 'Athagarh Agro Forest', lat: 20.5250, lng: 85.7350, area: 3.7, crop: 'rice', var: 'Lalat', days: 49 },
  { name: 'Banki Sub-Basin', lat: 20.3750, lng: 85.5350, area: 4.4, crop: 'rice', var: 'Swarna', days: 56 },
  { name: 'Nayagarh Hill Slope', lat: 20.1250, lng: 85.1050, area: 2.1, crop: 'tomato', var: 'Arka Rakshak', days: 48 },
];

export const SEED_FARMS: Farm[] = [
  DEMO_PRIMARY_FARM,
  ...REGION_OFFSETS.map((item, idx) => ({
    id: `seed-farm-${idx + 1}`,
    user_id: `seed-user-${idx + 1}`,
    name: item.name,
    lat: item.lat,
    lng: item.lng,
    area_acres: item.area,
    crop_id: item.crop,
    crop: SEED_CROPS.find(c => c.id === item.crop) || SEED_CROPS[0],
    variety: item.var,
    sowing_date: new Date(Date.now() - item.days * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    is_demo: false,
    created_at: new Date(Date.now() - (item.days + 5) * 24 * 60 * 60 * 1000).toISOString(),
  })),
];

// Seeded Disease Reports: 12 reports within 5km radius of Cuttack (Rice Blast Outbreak Cluster)
export const SEED_DISEASE_REPORTS: DiseaseReport[] = [
  {
    id: 'report-cluster-01',
    disease_id: 'rice_blast',
    disease: SEED_DISEASES[0],
    lat: 20.4635,
    lng: 85.8845, // 0.2 km from primary farm
    confidence: 0.92,
    severity: 'high',
    image_url: 'https://images.unsplash.com/photo-1599818816942-881b212f451f?auto=format&fit=crop&w=600&q=80',
    reported_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: false,
  },
  {
    id: 'report-cluster-02',
    disease_id: 'rice_blast',
    disease: SEED_DISEASES[0],
    lat: 20.4680,
    lng: 85.8910, // ~1.1 km
    confidence: 0.88,
    severity: 'moderate',
    image_url: 'https://images.unsplash.com/photo-1599818816942-881b212f451f?auto=format&fit=crop&w=600&q=80',
    reported_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  {
    id: 'report-cluster-03',
    disease_id: 'rice_blast',
    disease: SEED_DISEASES[0],
    lat: 20.4570,
    lng: 85.8750, // ~1.2 km
    confidence: 0.85,
    severity: 'high',
    reported_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  {
    id: 'report-cluster-04',
    disease_id: 'rice_blast',
    disease: SEED_DISEASES[0],
    lat: 20.4720,
    lng: 85.8890, // ~1.3 km
    confidence: 0.91,
    severity: 'critical',
    reported_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  {
    id: 'report-cluster-05',
    disease_id: 'rice_blast',
    disease: SEED_DISEASES[0],
    lat: 20.4510,
    lng: 85.8950, // ~1.8 km
    confidence: 0.84,
    severity: 'moderate',
    reported_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  {
    id: 'report-cluster-06',
    disease_id: 'rice_blast',
    disease: SEED_DISEASES[0],
    lat: 20.4650,
    lng: 85.8690, // ~1.4 km
    confidence: 0.79,
    severity: 'moderate',
    reported_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  {
    id: 'report-cluster-07',
    disease_id: 'rice_blast',
    disease: SEED_DISEASES[0],
    lat: 20.4790,
    lng: 85.8980, // ~2.5 km
    confidence: 0.90,
    severity: 'high',
    reported_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  {
    id: 'report-cluster-08',
    disease_id: 'rice_blast',
    disease: SEED_DISEASES[0],
    lat: 20.4430,
    lng: 85.8710, // ~2.6 km
    confidence: 0.82,
    severity: 'moderate',
    reported_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  {
    id: 'report-cluster-09',
    disease_id: 'rice_blast',
    disease: SEED_DISEASES[0],
    lat: 20.4850,
    lng: 85.9050, // ~3.3 km
    confidence: 0.87,
    severity: 'high',
    reported_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  {
    id: 'report-cluster-10',
    disease_id: 'rice_blast',
    disease: SEED_DISEASES[0],
    lat: 20.4350,
    lng: 85.8620, // ~3.7 km
    confidence: 0.78,
    severity: 'moderate',
    reported_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  {
    id: 'report-cluster-11',
    disease_id: 'rice_blast',
    disease: SEED_DISEASES[0],
    lat: 20.4920,
    lng: 85.9150, // ~4.5 km
    confidence: 0.86,
    severity: 'high',
    reported_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  {
    id: 'report-cluster-12',
    disease_id: 'rice_blast',
    disease: SEED_DISEASES[0],
    lat: 20.4280,
    lng: 85.8550, // ~4.8 km
    confidence: 0.89,
    severity: 'critical',
    reported_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  // Cluster 2: Bacterial Leaf Blight Cluster (Balasore / Soro Coast)
  {
    id: 'report-bb-01',
    disease_id: 'bacterial_blight',
    disease: SEED_DISEASES[1],
    lat: 21.2850,
    lng: 86.6900,
    confidence: 0.89,
    severity: 'high',
    reported_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  {
    id: 'report-bb-02',
    disease_id: 'bacterial_blight',
    disease: SEED_DISEASES[1],
    lat: 21.2910,
    lng: 86.6950,
    confidence: 0.86,
    severity: 'critical',
    reported_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  {
    id: 'report-bb-03',
    disease_id: 'bacterial_blight',
    disease: SEED_DISEASES[1],
    lat: 21.2780,
    lng: 86.6840,
    confidence: 0.82,
    severity: 'moderate',
    reported_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  {
    id: 'report-bb-04',
    disease_id: 'bacterial_blight',
    disease: SEED_DISEASES[1],
    lat: 21.2820,
    lng: 86.7010,
    confidence: 0.88,
    severity: 'high',
    reported_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },

  // Cluster 3: Sheath Blight Cluster (Jagatsinghpur / Tirtol Delta Hub)
  {
    id: 'report-sb-01',
    disease_id: 'sheath_blight',
    disease: SEED_DISEASES[2],
    lat: 20.3150,
    lng: 86.3200,
    confidence: 0.85,
    severity: 'moderate',
    reported_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  {
    id: 'report-sb-02',
    disease_id: 'sheath_blight',
    disease: SEED_DISEASES[2],
    lat: 20.3220,
    lng: 86.3280,
    confidence: 0.91,
    severity: 'high',
    reported_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  {
    id: 'report-sb-03',
    disease_id: 'sheath_blight',
    disease: SEED_DISEASES[2],
    lat: 20.3090,
    lng: 86.3140,
    confidence: 0.79,
    severity: 'moderate',
    reported_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  {
    id: 'report-sb-04',
    disease_id: 'sheath_blight',
    disease: SEED_DISEASES[2],
    lat: 20.3180,
    lng: 86.3310,
    confidence: 0.87,
    severity: 'high',
    reported_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },

  // Cluster 4: Tomato Early Blight Cluster (Pipili & Delanga Vegetable Zone)
  {
    id: 'report-tb-01',
    disease_id: 'tomato_early_blight',
    disease: SEED_DISEASES[4] || SEED_DISEASES[0],
    lat: 20.1150,
    lng: 85.8320,
    confidence: 0.92,
    severity: 'critical',
    reported_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  {
    id: 'report-tb-02',
    disease_id: 'tomato_early_blight',
    disease: SEED_DISEASES[4] || SEED_DISEASES[0],
    lat: 20.1220,
    lng: 85.8410,
    confidence: 0.88,
    severity: 'high',
    reported_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  {
    id: 'report-tb-03',
    disease_id: 'tomato_early_blight',
    disease: SEED_DISEASES[4] || SEED_DISEASES[0],
    lat: 20.1080,
    lng: 85.8250,
    confidence: 0.84,
    severity: 'moderate',
    reported_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  {
    id: 'report-tb-04',
    disease_id: 'tomato_early_blight',
    disease: SEED_DISEASES[4] || SEED_DISEASES[0],
    lat: 20.1180,
    lng: 85.8390,
    confidence: 0.90,
    severity: 'high',
    reported_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },

  // Cluster 5: Brown Spot Cluster (Bhadrak & Jajpur River Basin)
  {
    id: 'report-bs-01',
    disease_id: 'brown_spot',
    disease: SEED_DISEASES[3] || SEED_DISEASES[0],
    lat: 21.0550,
    lng: 86.5100,
    confidence: 0.86,
    severity: 'moderate',
    reported_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  {
    id: 'report-bs-02',
    disease_id: 'brown_spot',
    disease: SEED_DISEASES[3] || SEED_DISEASES[0],
    lat: 21.0620,
    lng: 86.5180,
    confidence: 0.83,
    severity: 'high',
    reported_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  {
    id: 'report-bs-03',
    disease_id: 'brown_spot',
    disease: SEED_DISEASES[3] || SEED_DISEASES[0],
    lat: 21.0490,
    lng: 86.5020,
    confidence: 0.81,
    severity: 'moderate',
    reported_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
  {
    id: 'report-bs-04',
    disease_id: 'brown_spot',
    disease: SEED_DISEASES[3] || SEED_DISEASES[0],
    lat: 21.0580,
    lng: 86.5150,
    confidence: 0.87,
    severity: 'high',
    reported_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    verified: true,
    is_simulated: true,
  },
];

// Pre-seeded Demo Diagnosis for Odisha Farm (per PRD §8)
export const DEMO_PRIMARY_DIAGNOSIS: Diagnosis = {
  id: 'demo-diag-rice-blast-01',
  farm_id: DEMO_FARM_ID,
  image_url: 'https://images.unsplash.com/photo-1599818816942-881b212f451f?auto=format&fit=crop&w=800&q=80',
  disease_id: 'rice_blast',
  disease: SEED_DISEASES[0],
  confidence: 0.87,
  severity: 'moderate',
  analysis_json: {
    crop: 'rice',
    primary_disease: 'rice_blast',
    confidence: 0.87,
    severity: 'moderate',
    alternative_diagnoses: [
      { disease: 'brown_spot', disease_name: 'Brown Spot', confidence: 0.09 },
      { disease: 'bacterial_blight', disease_name: 'Bacterial Blight', confidence: 0.04 },
    ],
    visual_evidence: [
      'Spindle-shaped elliptical lesions with grayish centers',
      'Brown necrotic margins on upper leaf blades',
      'Initial lesion coalescence on vegetative tillers',
    ],
    image_quality: 0.92,
  },
  created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
};

// Seeded Alerts for the Demo Farm
export const SEED_ALERTS: Alert[] = [
  {
    id: 'alert-demo-01',
    farm_id: DEMO_FARM_ID,
    type: 'outbreak',
    title: 'Outbreak Warning: Rice Blast Cluster Detected',
    message: '12 active Rice Blast reports detected within 5 km of your farm in the last 7 days. Risk pressure is Critical (81/100).',
    severity: 'critical',
    read: false,
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-demo-02',
    farm_id: DEMO_FARM_ID,
    type: 'weather_risk',
    title: 'High Humidity & Continuous Leaf Wetness Alert',
    message: 'Forecast indicates 88% average humidity with overnight dew for the next 4 days, highly accelerating fungal sporulation.',
    severity: 'high',
    read: false,
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
];
